# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camSettingsUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_camSettingsDialog(object):
    def setupUi(self, camSettingsDialog):
        
        camSettingsDialog.setObjectName("camSettingsDialog")
        camSettingsDialog.resize(1488, 708)
        
        #DIALOG LAYOUT
        self.horizontalLayout = QtWidgets.QHBoxLayout(camSettingsDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        #LEFT SIDE FRAME
        self.settingsFrame1 = QtWidgets.QFrame(camSettingsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsFrame1.sizePolicy().hasHeightForWidth())
        self.settingsFrame1.setSizePolicy(sizePolicy)
        self.settingsFrame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settingsFrame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settingsFrame1.setObjectName("settingsFrame1")
        
        #LEFT SIDE LAYOUT
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.settingsFrame1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        #BRIGHTNESS LABEL
        self.brightnessLabel = QtWidgets.QLabel(self.settingsFrame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brightnessLabel.sizePolicy().hasHeightForWidth())
        self.brightnessLabel.setSizePolicy(sizePolicy)
        self.brightnessLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brightnessLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.brightnessLabel.setObjectName("brightnessLabel")
        self.verticalLayout_2.addWidget(self.brightnessLabel)
        
        #BRIGHTNESS SLIDER
        self.brightnessSlider = QtWidgets.QSlider(self.settingsFrame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brightnessSlider.sizePolicy().hasHeightForWidth())
        self.brightnessSlider.setSizePolicy(sizePolicy)
        self.brightnessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.brightnessSlider.setObjectName("brightnessSlider")
        self.brightnessSlider.setMinimum(-64)
        self.brightnessSlider.setMaximum(64)
        
        self.verticalLayout_2.addWidget(self.brightnessSlider)
        
        #GAMMA LABEL
        self.gammaLabel = QtWidgets.QLabel(self.settingsFrame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gammaLabel.sizePolicy().hasHeightForWidth())
        self.gammaLabel.setSizePolicy(sizePolicy)
        self.gammaLabel.setObjectName("gammaLabel")
        self.verticalLayout_2.addWidget(self.gammaLabel)
        self.gammaSlider = QtWidgets.QSlider(self.settingsFrame1)
        self.gammaSlider.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gammaSlider.sizePolicy().hasHeightForWidth())
        
        #GAMMA SLIDER
        self.gammaSlider.setSizePolicy(sizePolicy)
        self.gammaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gammaSlider.setObjectName("gammaSlider")
        self.brightnessSlider.setMinimum(40)
        self.brightnessSlider.setMaximum(500)
        self.brightnessSlider.setTickInterval(1)
        self.brightnessSlider.setTickPosition(3)
        
        self.verticalLayout_2.addWidget(self.gammaSlider)
        
        #SHARPNESS LABEL
        self.sharpnessLabel = QtWidgets.QLabel(self.settingsFrame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sharpnessLabel.sizePolicy().hasHeightForWidth())
        self.sharpnessLabel.setSizePolicy(sizePolicy)
        self.sharpnessLabel.setObjectName("sharpnessLabel")
        self.verticalLayout_2.addWidget(self.sharpnessLabel)
        
        #SHARPNESS SLIDER
        self.sharpnessSlider = QtWidgets.QSlider(self.settingsFrame1)
        self.sharpnessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sharpnessSlider.setObjectName("sharpnessSlider")
        self.verticalLayout_2.addWidget(self.sharpnessSlider)
        self.sharpnessSlider.setMinimum(0)
        self.sharpnessSlider.setMaximum(128)
        
        #PAN LABEL
        self.panLabel = QtWidgets.QLabel(self.settingsFrame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panLabel.sizePolicy().hasHeightForWidth())
        self.panLabel.setSizePolicy(sizePolicy)
        self.panLabel.setObjectName("panLabel")
        self.verticalLayout_2.addWidget(self.panLabel)
        
        #PAN SLIDER
        self.panSlider = QtWidgets.QSlider(self.settingsFrame1)
        self.panSlider.setOrientation(QtCore.Qt.Horizontal)
        self.panSlider.setObjectName("panSlider")
        self.verticalLayout_2.addWidget(self.panSlider)
        
        #TILT LABEL
        self.tiltLabel = QtWidgets.QLabel(self.settingsFrame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tiltLabel.sizePolicy().hasHeightForWidth())
        self.tiltLabel.setSizePolicy(sizePolicy)
        self.tiltLabel.setObjectName("tiltLabel")
        self.verticalLayout_2.addWidget(self.tiltLabel)
        
        #TILT SLIDER
        self.tiltSlider = QtWidgets.QSlider(self.settingsFrame1)
        self.tiltSlider.setOrientation(QtCore.Qt.Horizontal)
        self.tiltSlider.setObjectName("tiltSlider")
        self.verticalLayout_2.addWidget(self.tiltSlider)
        
        #ADD LEFT FRAME
        self.horizontalLayout.addWidget(self.settingsFrame1)
        
        #RIGHT SIDE FRAME
        self.settingsFrame2 = QtWidgets.QFrame(camSettingsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsFrame2.sizePolicy().hasHeightForWidth())
        self.settingsFrame2.setSizePolicy(sizePolicy)
        self.settingsFrame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settingsFrame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settingsFrame2.setObjectName("settingsFrame2")
        
        #RIGHT SIDE LAYOUT
        self.verticalLayout = QtWidgets.QVBoxLayout(self.settingsFrame2)
        self.verticalLayout.setObjectName("verticalLayout")
        
        #RESOLUTION LABEL
        self.resolutionLabel = QtWidgets.QLabel(self.settingsFrame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resolutionLabel.sizePolicy().hasHeightForWidth())
        self.resolutionLabel.setSizePolicy(sizePolicy)
        self.resolutionLabel.setObjectName("resolutionLabel")
        self.verticalLayout.addWidget(self.resolutionLabel)
        
        #RESOLUTION SELECTION BOX
        self.resolutionBox = QtWidgets.QComboBox(self.settingsFrame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resolutionBox.sizePolicy().hasHeightForWidth())
        self.resolutionBox.setSizePolicy(sizePolicy)
        self.resolutionBox.setObjectName("resolutionBox")
        self.verticalLayout.addWidget(self.resolutionBox)
        
        #RESET TO DEFAULT BUTTON 
        self.defaultResetButton = QtWidgets.QPushButton(self.settingsFrame2)
        self.defaultResetButton.setObjectName("defaultResetButton")
        self.verticalLayout.addWidget(self.defaultResetButton)
        
        #OKAY BUTTON
        self.okButton = QtWidgets.QPushButton(self.settingsFrame2)
        self.okButton.setObjectName("okButton")
        self.verticalLayout.addWidget(self.okButton)
        self.horizontalLayout.addWidget(self.settingsFrame2)

        self.retranslateUi(camSettingsDialog)
        QtCore.QMetaObject.connectSlotsByName(camSettingsDialog)

    def retranslateUi(self, camSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        camSettingsDialog.setWindowTitle(_translate("camSettingsDialog", "Camera Settings"))
        self.brightnessLabel.setText(_translate("camSettingsDialog", "Brightness"))
        self.gammaLabel.setText(_translate("camSettingsDialog", "Gamma"))
        self.sharpnessLabel.setText(_translate("camSettingsDialog", "Sharpness"))
        self.panLabel.setText(_translate("camSettingsDialog", "Pan"))
        self.tiltLabel.setText(_translate("camSettingsDialog", "Tilt"))
        self.resolutionLabel.setText(_translate("camSettingsDialog", "Resolution"))
        self.defaultResetButton.setText(_translate("camSettingsDialog", "Reset to Default"))
        self.okButton.setText(_translate("camSettingsDialog", "OK"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     camSettingsDialog = QtWidgets.QDialog()
#     ui = Ui_camSettingsDialog()
#     ui.setupUi(camSettingsDialog)
#     camSettingsDialog.show()
#     sys.exit(app.exec_())
